require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

inherit_gem:
  rubocop-lts: rubocop-lts.yml

AllCops:
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - vendor/**/*

# Bundler

Bundler/GemComment:
  Enabled: true

# Gemspec

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

# Layout

# Errors out on Ruby 3.1.3
Layout/BlockAlignment:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

# No space inside Hash literals, e.g. {key: "value"}
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# Lint

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

# Metrics

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - service_actor.gemspec

Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/**/*
    - service_actor.gemspec

# RSpec

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

# Style

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

# Allow using the second parameter as a boolean.
Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses
