require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

Bundler/GemComment:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - service_actor.gemspec

Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/**/*
    - service_actor.gemspec

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/OpenStructUse:
  Enabled: false

# Allow using the second parameter as a boolean.
Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
