require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

inherit_gem:
  rubocop-lts: rubocop-lts.yml

AllCops:
  Exclude:
    - bin/rake
    - bin/rspec
    - bin/rubocop

Bundler/GemComment:
  Enabled: true

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - service_actor.gemspec

Metrics/MethodLength:
  Max: 12
  Exclude:
    - spec/**/*
    - service_actor.gemspec

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

# Allow using the second parameter as a boolean.
Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/DoubleNegation:
  Enabled: false

Style/StabbyLambdaParentheses:
  EnforcedStyle: require_no_parentheses

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
