name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Test and lint with rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
